// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("fsharping-ddd")>]
[<assembly: AssemblyProductAttribute("Fsharping DDD")>]
[<assembly: AssemblyDescriptionAttribute("Repository for a DDD workshop in Fsharping meetup.")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.0")>]
[<assembly: InternalsVisibleToAttribute("tests")>]
[<assembly: AssemblyMetadataAttribute("gitbranch","master")>]
[<assembly: AssemblyMetadataAttribute("gitcommit","b32d25ab7413f789f92e5b90ce51317e08cad966")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fsharping-ddd"
    let [<Literal>] AssemblyProduct = "Fsharping DDD"
    let [<Literal>] AssemblyDescription = "Repository for a DDD workshop in Fsharping meetup."
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyFileVersion = "0.0.0"
    let [<Literal>] InternalsVisibleTo = "tests"
    let [<Literal>] AssemblyMetadata_gitbranch = "master"
    let [<Literal>] AssemblyMetadata_gitcommit = "b32d25ab7413f789f92e5b90ce51317e08cad966"
